### ISSUE TITLE
[Question] is there a way to see who is online through the API ?

### ISSUE THREAD

**Issue by helen-fornazier** [workadventure/scripting-api-extra#229]
Hi,

first, thanks for this project, really nice!

I was reading the API and I couldn't find a way to check if a member is online or not, is there a way of doing that?

Thanks!

**Comment by moufmouf** [comment]
Hey @helen-fornazier ,

You should file the issues to https://github.com/workadventure/workadventure instead.

To answer your question, you can listen to players around you with:

https://docs.workadventu.re/developer/map-scripting/references/api-players/

It will return all players within the viewport.
There is however currently no way to track players anywhere on the map.
