### ISSUE TITLE
Cannot find "/distconfiguration.html" in @workadventure/scripting-api-extra@1.0.4

### ISSUE THREAD

**Issue by s00500** [workadventure/scripting-api-extra#53]
Hey!

First of all SUPER AWESOME STUFF WITH THE SCRIPTING!!!!!!!!!!!

Second of all: found a bug!

If I load the scripting api into my map using the map properties with
https://unpkg.com/@workadventure/scripting-api-extra@1.0.4/dist/bundle.js

And then try to add a config screen and open it I get this error:
Cannot find "/distconfiguration.html" in @workadventure/scripting-api-extra@1.0.4

I definitly see the missing slash between dist and configuration.html
I also did not test the doors with keypad but I think they would fail because of the same reason.

I have "fixed" the issue for myself by changing the asset url in default_asset_url.ts, then rebuilding and selfhosting the script on my own server. With this in place it works just as intended!

But I would assume that it should also work with the version from unpkg.com :-)
Should be fairly easy to solve I guess

Greetings,
Lukas

**Comment by moufmouf** [comment]
Hey @s00500 ,

Thanks a lot for reporting this issue.
It is now fixed in version 1.0.5.

:+1:

**Comment by s00500** [comment]
Awesome thanks =D
