### ISSUE TITLE
Variable based Layer Visibility lost when switching rooms

### ISSUE THREAD

**Issue by s00500** [workadventure/scripting-api-extra#77]
I have 2 rooms, each of them uses variables to set the visibility of an overlay layer using the configuration menu. This works fine, but when changing rooms using the zones the variables get reset and the layers will always be visible, no matter what...

The only way to get them back to the desired state is to do a full page reload in the new room. So this is definitly a problem of the frontend / scripting extension as the server side var state seems to stay correct

**Comment by s00500** [comment]
Hey @moufmouf, sorry was a busy week, here is the map

https://maps.wa.lbs.sh/Schaumi/cellar/map.json

**Comment by s00500** [comment]
If you select configure the room there is a layer called strange portal, it is just a bunch of brown blocks near the staircase in the top, toggle it on and off, then go to trough the stairs into the cellar, then go back up and find that the visibility has reevaluated to true, although the variable in configure the room is still correct

**Comment by s00500** [comment]
This issue still seems to be valid, could you reproduce it yet ?

**Comment by moufmouf** [comment]
Hey @s00500 ,

Ok, I can confirm I can reproduce the issue.
I'm really sorry, I failed to see the notification of your issue. And to be honest, I have been struggling to reproduce this exact bug and you have here the perfect example to reproduce it reliably.

I'll take a look ASAP.

**Comment by s00500** [comment]
Ok awesome, thanks for the feedback :-)

**Comment by moufmouf** [comment]
I found the issue! A fix is incoming here: https://github.com/thecodingmachine/workadventure/pull/1638

Once again, thanks for opening this ticket, it really pointed me in the right direction.

The fix should be deployed some time next week.

**Comment by s00500** [comment]
@moufmouf this is so awesome to hear, as a fellow software dev I happen to have seen quite a few such magic issues (where underlying memory behaves different than imagined) so I know the pain of not having a reproducible setup very well, great work! thanks

**Comment by s00500** [comment]
After testing on v1.6.4 today I can confirm the fix works fine, the layer is still visible on room change for a very short amount of time though, but I would need to experiment further to see if this can be avoided...
